services:
  app:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    container_name: api
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - database
    env_file: ./.env

  database:
    image: postgres:13
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local